# celery_manager/Dockerfile.celery

# Use a imagem base do Python
FROM python:3.9-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia TODO o projeto para o contêiner
COPY .. .

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Define a variável de ambiente PYTHONPATH
ENV PYTHONPATH="/app"

# Comando para iniciar o worker do Celery
CMD ["celery", "-A", "celeryManager.celery_app", "worker", "--loglevel=info"]