# celery_manager/Dockerfile.worker_ops

FROM python:3.9-slim
WORKDIR /app
COPY . .
COPY ../interface ./interface
ENV PYTHONPATH="/app"
RUN pip install --no-cache-dir -r requirements.txt

CMD ["celery", "--app", "celery_app", "worker", "--concurrency=10", "-Q", "operations", "-n", "worker_ops@%h", "--loglevel=info"]
