# celery_manager/Dockerfile.worker_db

FROM python:3.9-slim
WORKDIR /app
COPY . .
ENV PYTHONPATH="/app"
RUN pip install --no-cache-dir -r requirements.txt

CMD ["celery", "--app", "celery_app", "worker", "--concurrency=4", "-Q", "db", "-n", "worker_db@%h", "--loglevel=info"]
