# Usa uma imagem base do Python
FROM python:3.9

# Define o diretório de trabalho no contêiner
WORKDIR /app

# Copia todo o projeto para o contêiner
COPY . .

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Define a variável de ambiente PYTHONPATH para garantir que os módulos possam ser encontrados
ENV PYTHONPATH="/app"

# Comando para iniciar o Celery Worker
CMD ["celery", "-A", "webhookReceiver.celery_manager.celery_app", "worker", "--loglevel=info"]
