# Use a Python 3.9 base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the entire project into the container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set PYTHONPATH to include the /app directory
ENV PYTHONPATH="/app"

# Command to start the Celery Worker
CMD ["celery", "-A", "webhookReceiver.celery_manager.tasks", "worker", "--loglevel=info"]